name: twitch
description: >
  Unofficial Twitch API for Dart and Flutter.
version: 0.3.2
authors:
  - Brian Egan <brian@brianegan.com>
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/twitch.dart

environment:
  sdk: ">=1.22.0 <2.0.0"

dependencies:
  meta: ^1.0.5

dev_dependencies:
  stack_trace: ^1.3.2
  test: ^0.12.20+12
