name: twitch
description: >
  Unofficial Twitch client for Dart and Flutter.
version: 0.1.0+1
authors:
  - Matan Lurey <matanl@google.com>
homepage: https://github.com/matanlurey/twitch.dart

environment:
  sdk: ">=1.22.0 <2.0.0"

dev_dependencies:
  stack_trace: ^1.3.2
  test: ^0.12.20+12
